- name: Create a database to save the information
  mysql_db:
    name: '{{database_name}}'
    state: present

- name: create tables for the database
  mysql_db: 
    name: '{{database_name}}'
    state: import 
    target: /home/project/create-table.sql
